In [ ]:
generator, syntax, modules(file with .py), iterator, package, library
4 rules of variable naming in Python:
- It cannot be a keyword: https://docs.python.org/3/reference/lexical_analysis.html#keywords
- It can only contain A-z, 0-9, _
- case-sensitive, e.g. X is not the same as x
- cannot start with a number, e.g. can only be x1, not 1x

2 conventions of variable naming: 
- snake_case, e.g. age_of_puppycat = 12
- camelCase, e.g. ageOfPuppycat = 12
+(str&int) - * / // % ^

slicing: start:end:step [: :]

Objects are Python's abstractions of data.

https://docs.python.org/3/reference/datamodel.html#objects-values-and-types

In `x = 0`, then `0` is the object, and `x` is the name (variable name).

An object has 3 things:
- an identity: basically object's address in memory. use `id()`
- a type: use `type()`
- a value

is可以比较id， == 比较value和type

immutable：str, tuple
mutable: list

```Python
x = 0
y = 1
z = 2

print(x < y <= z)

print(len("") > 0 and y < z) # A and B: if A is False, doesn't evaluate B.

print(len("") > 0 or y < z) # A or B: if A is True, doesn't evaluate B.

print(not (x == y), x != y)

```

`if, elif, else` `while, break` `continue` (go back to top of the innermost loop it's in) `pass` `enumerate` `yield` `raise`

*args = get all the positional arguments in a tuple called args. 
*kwargs = get all the keyword arguments in a dict called kwargs.

class variables: shared across all instances

Define new class A that inherits from B by writing
```
class A(B):
    pass 
```

syntax error is error in using Python language, grammatical errors.

runtime errors (exceptions) are everything else, computer can't follow the instruction.

`raise`: when you `raise` an exception, it immediately halts the execution of the code.

`try` to do whatever you were trying to do, and if Python raises an exception, `except` it and run something else instead of stopping your code all together

try:

    # what to do with expected input
except TypeError:

    # if your input type is wrong
    
finally:


For an object `L` to be iterable ('for-loop-able'),

1. `L` has __iter__ method implemented so that `iter(L)` returns an iterator
2. that iterator returned by `iter(L)` has __next__ method implemented
```Python
class boringList:
    def __init__(self, L):
        self.L = L
    
    def __str__(self):
        return str(self.L)
    
    def __iter__(self):
        print('boringList __iter__')
        return boringListIterator(self) 
    # self is an instance of boringList
    # typically pass self so that itator can have access to all of self's stuff
     
class boringListIterator:
    def __init__(self, bL): # here self is an instance of boringListIterator, and bL is expected to be an instance of boringList
        self.L = bL.L
        self.i = 0 # keeps track of current index
        print('boringListIterator __init__')
    
    def __next__(self):
        print('boringListIterator __next__')
        if self.i < len(self.L):
            element = self.L[self.i] # access the i-th element
            self.i += 1 # indicate where to look next
            return element
        else:
            raise StopIteration

# shorter version of the same code:
#    def __next__(self):
#         if self.i >= len(self.L):
#             raise StopIteration
        
#         self.i += 1
#         return(self.L[self.i-1])

B = boringList([1,2,3])
print(B)

for i in B:
    print(i)
    
```

In [ ]:
import random
from random import choices, gauss
import numpy as np 
import math
print()
type()
len()
copy()
x = lambda n: print(n)
isinstance(obj, class)
issubclass(class A, class B)
random.choices([1,2,3,4])
random.random()
random.gauss(5, 1)
x = np.array([1,2,3,4])
%timeit
a = np.linspace(0, 2*np.pi, 101) # from 0 (inclusive) to 2*np.pi (inclusive), get 101 evenly spaced points
np.random.rand(n) # n random numbers between 0 and 1 : Uniform([0, 1])
a = np.zeros(n) 
a = np.ones(n)
np.arange(n)
a.shape
a.reshape(3, 5)
A.T # setter methods
np.sum(a), a.sum()
np.random.randint(5) # Uniform({0, 1, 2, 3, 4})
np.any(a > 8) # return True if ANY of the array elements are True
np.all(a < 10) # return True if ALL of the array elements are True
A.sum(axis=0) # gives the totals in each column 
A.sum(axis=1) # gives the totals in each row
a.cumsum() # cumulative sum


string method: `strip`, `replace`, `split`, `splitlines`, `join`
https://docs.python.org/3/library/stdtypes.html#string-methods
```Python
s =  'aaahh   panic    aahhh'
print(s.strip('ah'))#    panic    
print(s.strip('ah '))# panic

L = ["ba", "na", "na"]
print("---".join(L))# ba---na---na

s = "Tired    : Doing math on your calculator.\nWired    : Doing math in Python.\nInspired : Training literal pythons to carry out long division using an abacus."
print(s.replace(': ', '\n'))
```

list method: `append`(不会改变位置，+会改变位置), 

https://docs.python.org/3/tutorial/datastructures.html#more-on-lists


dict method: keys(), values(), items(),update()

In [39]:
class TwoDArray(list):
    
    #part A
    def __init__(self, array):
        """
        Initialize an instance variable array with a list of lists that have the same length
        Args:
            array: a list variable 
        Returns:
            None
        """
        
        ##########################
        if not isinstance(array, list) & all(isinstance(i, list) for i in array):
            raise TypeError("This function is designed to work only with list of lists.")
        elif len(array)>1 and all(len(array[0]) != len(i) for i in array[1:]):
            raise ValueError("All lists need to have the same length.")   
        ############################
        
        #this line is written for you
        self.array=array
        
    #I am giving you these for free to save you time
    def __str__(self):
        return '[' + "\n ".join([str(arr) for arr in self.array]) + ']'
    
    def shape(self):
        return (len(self.array), len(self.array[0]))

    
    #part B
    def __rmul__(self, c): 
        m, n = self.shape()
        
        #################################
        return [[c*self.array[row][col] for col in range(n)] for row in range(m)] 
        #################################
    
    #Part C
    def __add__(self, other):
        """
        Add two TwoDArrays as two numpys followed by the rules of broadcasting.
        """
            
        ##########################
        result = TwoDArray([])
        if not (isinstance(self, TwoDArray) & isinstance(other, TwoDArray)):
            raise TypeError ("Two instances should be TwoDArrays!")     
        ############################

        ############ DO NOT CHANGE ############
        #dummy variables for shorter lines
        sa, oa = self.array, other.array
        #array dimesnions
        m, n = self.shape()
        m1, n1 = other.shape()
        ########################################
        

        if m==m1 and n==n1:       # same shape, add items at the same position
            result.array = [[sa[r][c] + oa[r][c] for c in range(n)] for r in range(m)]  
        elif m==m1 and n==1:      # sa is m-by-1 matrix, boardcast it to m-by-n1
            sa = TwoDArray([(sa[r]*n1) for r in range(m)])
            result = sa.__add__(TwoDArray(oa))
        elif m==1 and n==n1:      # sa is 1-by-n matrix, boardcast it to m1-by-n 
            result = TwoDArray(oa).__add__(TwoDArray(sa*m1))     
        elif (m==m1 and n1==1) or (m1==1 and n==n1): #oa is 1-by-n or m-by-1
            result = TwoDArray(oa).__add__(TwoDArray(sa))
        else:
            pass # replace with your solution
    
        return result
    #part D
    def __sub__(self, other):
        return self.__add__(TwoDArray([[-num for num in lis] for lis in other.array]))
    
    #Part E
    #I have written this method for you to save time
    def __iter__(self):
        return TwoDArrayIterator(self)
    
#more part E
class TwoDArrayIterator:
    
    #### DO NOT CHANGE ##############
    def __init__(self, TDA):
        self.array = TDA.array
        self.i, self.j = 0, 0 #tracker for row index and column index
        self.m, self.n = TDA.shape()
    ################################
      
    def __next__(self):
        if self.j ==  self.n:
            self.j = 0
            self.i += 1
            if self.i == self.m :
                raise StopIteration
        num = self.array[self.i][self.j]
        self.j += 1
        return num   

        
                    

In [40]:
x=TwoDArray([[1,2],[3,4]])
for t in x:
    print(t)

1
2


TypeError: __next__() takes 1 positional argument but 3 were given

In [18]:
x=TwoDArray([[0,0],[0,0]])
y=TwoDArray([[0,0],[0,0]])
z=TwoDArray([[1],[2]])
w=TwoDArray([[1,2]])
print(x-y)
print(x-z)
print(x-w)
print(z-x)
print(w-x)

[[0, 0]
 [0, 0]]
[[-1, -1]
 [-2, -2]]
[[-1, -2]
 [-1, -2]]
[[1, 1]
 [2, 2]]
[[1, 2]
 [1, 2]]


In [44]:
import numpy as np


x=np.array([[0,0],[0,0]])
y=np.array([[0,0],[0,0]])
z=np.array([[1],[2]])
w=np.array([[1,2]])
print(x-y)
print(x-z)
print(x-w)
print(z-x)
print(w-x)

[[0 0]
 [0 0]]
[[-1 -1]
 [-2 -2]]
[[-1 -2]
 [-1 -2]]
[[1 1]
 [2 2]]
[[1 2]
 [1 2]]
